ncl dv500_extract.ncl
#ncl dvs_extract.ncl
ncl hur500_extract.ncl
#ncl hurs_extract.ncl
ncl hus500_extract.ncl
#ncl pr_extract.ncl
#ncl psl_extract.ncl
#ncl tas_extract.ncl
ncl ua500_extract.ncl
#ncl uas_extract.ncl
ncl va500_extract.ncl
#ncl vas_extract.ncl
ncl vr500_extract.ncl
#ncl vrs_extract.ncl
ncl wd500_extract.ncl
#ncl wds_extract.ncl
ncl ws500_extract.ncl
#ncl wss_extract.ncl
ncl zg500_extract.ncl

echo 'DoNe!'